var KEY_STAR = "KEY_STAR";
var KEY_BACKGROUND = "KEY_BACKGROUND";
var KEY_DEADZONE = "KEY_DEADZONE";
var KEY_CLOCK = "KEY_CLOCK";
var KEY_PLATE = "KEY_PLATE";
var KEY_BACKGROUND_CLOCK = "KEY_BACKGROUND_CLOCK";
var KEY_CTA_BUTTON = "KEY_CTA_BUTTON";